### ISSUE TITLE
AMBER: Apertif Monitor for Bursts Encountered in Real-Time

### ISSUE THREAD

**Issue by isazi** [NLeSC/TEAM2018#23]
**Title**: AMBER, the Apertif Monitor for Bursts Encountered in Real-Time

**Software Package**: [AMBER](https://github.com/AA-ALERT/AMBER)

**Editor**: myself

**Notes**: AMBER is the real-time pipeline for detecting Fast Radio Bursts in real-time developed for the AA-ALERT project.

**Comment by isazi** [comment]
Asked Ben for comments, will submit after his comments are implemented.

**Comment by romulogoncalves** [comment]
For the 4 days of the sprint the people to who this issue is assigned should report hours on:
AA-ALERT project (@isazi what is the project code?)

Only report the days you were present at the Sprint. If you switched teams, report that days in the project specified in the issue of that team.

For extra work you need to request time to the tech leads by sending an email to techleads@esciencecenter.nl

**Comment by romulogoncalves** [comment]
@isazi once the paper is submitted, please let us through a comment on this issue and close the issue.

**Comment by romulogoncalves** [comment]
@isazi we would like to know if the paper was submitted?

**Comment by isazi** [comment]
It was not, we are still waiting for comments.

**Comment by romulogoncalves** [comment]
@isazi could you let us know if the paper was submitted? 
Thanks

**Comment by isazi** [comment]
Now that the eScience conference is over Ben has more time and should be able to give comments on the paper, and then we will submit it to SoftwareX.

**Comment by isazi** [comment]
Update. Ben worked on the paper, and the goal is to submit it to SoftwareX before the holidays.

**Comment by isazi** [comment]
We just submitted the paper to SoftwareX.
