### ISSUE TITLE
SPOT demo

### ISSUE THREAD

**Issue by fdiblen** [NLeSC/TEAM2018#32]
# Sprint Name 
SPOT-If-I...
# Team leader
Faruk
# Target project 
IDARK / SPOT
# Expertise required
- Ability to use a web browser, keyboard and mouse
# Size of team
3 - 5
# Description
[SPOT](https://github.com/nlesc/spot) is a generic visual data analytics tool for multi-dimensional
datasets. Although, it was primarily developed for High Energy Physics project [IDARK](https://www.esciencecenter.nl/project/idark), it is a generic software that can be used in some other domains where the dataset is complex.
Currently, we have a demo using famous Titanic dataset (see http://spot.esciencecenter.nl).
# Goals
- The main goal will be to focus on finding a nice (scientific) use case and an interesting datasets for a demo
- The demo will be used in external presentations and SPOT workshops which we are planning to organize when the materials are ready
- Update the demo web site
- Dockerize the demo
- Identify missing features to be used in certain domains

**Comment by romulogoncalves** [comment]
For the 4 days of the sprint the people to who this issue is assigned should report hours on:
iDark (@fdiblen what is the project code)

Only report the days you were present at the Sprint. If you switched teams, report that days in the project specified in the issue related with it.

For extra work you need to request time to the tech leads by sending an email to techleads@esciencecenter.nl

**Comment by romulogoncalves** [comment]
@fdiblen please let us know if you extra time work in the content of the story line and external help (someone with specific expertise) to solve technical issues in the demo.
